# ---------------------------------------------------------------------------
# FCEUmm (GPL-2.0): vendored under third_party/cores/fceumm/, pinned to
# upstream commit b5e3566
# (https://github.com/libretro/FCEUmm/tree/b5e3566). See
# third_party/cores/fceumm/VENDORING.md for exactly what was vendored.
#
# Source list mirrors upstream's libretro/Makefile.common (SOURCES_C).
# ---------------------------------------------------------------------------

add_library(fceumm_core SHARED
    ${FCEUMM_DIR}/src/boards/__dummy_mapper.c
    ${FCEUMM_DIR}/src/boards/__serial.c
    ${FCEUMM_DIR}/src/boards/09-034a.c
    ${FCEUMM_DIR}/src/boards/103.c
    ${FCEUMM_DIR}/src/boards/104.c
    ${FCEUMM_DIR}/src/boards/106.c
    ${FCEUMM_DIR}/src/boards/108.c
    ${FCEUMM_DIR}/src/boards/112.c
    ${FCEUMM_DIR}/src/boards/116.c
    ${FCEUMM_DIR}/src/boards/117.c
    ${FCEUMM_DIR}/src/boards/120.c
    ${FCEUMM_DIR}/src/boards/121.c
    ${FCEUMM_DIR}/src/boards/122.c
    ${FCEUMM_DIR}/src/boards/126_422_534.c
    ${FCEUMM_DIR}/src/boards/128.c
    ${FCEUMM_DIR}/src/boards/12in1.c
    ${FCEUMM_DIR}/src/boards/134.c
    ${FCEUMM_DIR}/src/boards/14.c
    ${FCEUMM_DIR}/src/boards/15.c
    ${FCEUMM_DIR}/src/boards/151.c
    ${FCEUMM_DIR}/src/boards/156.c
    ${FCEUMM_DIR}/src/boards/162.c
    ${FCEUMM_DIR}/src/boards/163.c
    ${FCEUMM_DIR}/src/boards/164.c
    ${FCEUMM_DIR}/src/boards/168.c
    ${FCEUMM_DIR}/src/boards/170.c
    ${FCEUMM_DIR}/src/boards/174.c
    ${FCEUMM_DIR}/src/boards/175.c
    ${FCEUMM_DIR}/src/boards/177.c
    ${FCEUMM_DIR}/src/boards/178.c
    ${FCEUMM_DIR}/src/boards/18.c
    ${FCEUMM_DIR}/src/boards/182.c
    ${FCEUMM_DIR}/src/boards/183.c
    ${FCEUMM_DIR}/src/boards/185.c
    ${FCEUMM_DIR}/src/boards/186.c
    ${FCEUMM_DIR}/src/boards/187.c
    ${FCEUMM_DIR}/src/boards/189.c
    ${FCEUMM_DIR}/src/boards/190.c
    ${FCEUMM_DIR}/src/boards/191.c
    ${FCEUMM_DIR}/src/boards/193.c
    ${FCEUMM_DIR}/src/boards/195.c
    ${FCEUMM_DIR}/src/boards/199.c
    ${FCEUMM_DIR}/src/boards/206_486.c
    ${FCEUMM_DIR}/src/boards/208.c
    ${FCEUMM_DIR}/src/boards/21_22_23_25.c
    ${FCEUMM_DIR}/src/boards/213.c
    ${FCEUMM_DIR}/src/boards/218.c
    ${FCEUMM_DIR}/src/boards/222.c
    ${FCEUMM_DIR}/src/boards/225.c
    ${FCEUMM_DIR}/src/boards/228.c
    ${FCEUMM_DIR}/src/boards/230.c
    ${FCEUMM_DIR}/src/boards/232.c
    ${FCEUMM_DIR}/src/boards/233.c
    ${FCEUMM_DIR}/src/boards/234.c
    ${FCEUMM_DIR}/src/boards/235.c
    ${FCEUMM_DIR}/src/boards/236.c
    ${FCEUMM_DIR}/src/boards/237.c
    ${FCEUMM_DIR}/src/boards/239.c
    ${FCEUMM_DIR}/src/boards/242.c
    ${FCEUMM_DIR}/src/boards/244.c
    ${FCEUMM_DIR}/src/boards/246.c
    ${FCEUMM_DIR}/src/boards/252_253.c
    ${FCEUMM_DIR}/src/boards/265.c
    ${FCEUMM_DIR}/src/boards/266.c
    ${FCEUMM_DIR}/src/boards/267.c
    ${FCEUMM_DIR}/src/boards/268.c
    ${FCEUMM_DIR}/src/boards/269.c
    ${FCEUMM_DIR}/src/boards/272.c
    ${FCEUMM_DIR}/src/boards/273.c
    ${FCEUMM_DIR}/src/boards/277.c
    ${FCEUMM_DIR}/src/boards/28.c
    ${FCEUMM_DIR}/src/boards/280.c
    ${FCEUMM_DIR}/src/boards/283.c
    ${FCEUMM_DIR}/src/boards/285.c
    ${FCEUMM_DIR}/src/boards/291.c
    ${FCEUMM_DIR}/src/boards/293.c
    ${FCEUMM_DIR}/src/boards/294.c
    ${FCEUMM_DIR}/src/boards/298.c
    ${FCEUMM_DIR}/src/boards/301.c
    ${FCEUMM_DIR}/src/boards/308.c
    ${FCEUMM_DIR}/src/boards/31.c
    ${FCEUMM_DIR}/src/boards/310.c
    ${FCEUMM_DIR}/src/boards/319.c
    ${FCEUMM_DIR}/src/boards/32.c
    ${FCEUMM_DIR}/src/boards/321.c
    ${FCEUMM_DIR}/src/boards/326.c
    ${FCEUMM_DIR}/src/boards/33.c
    ${FCEUMM_DIR}/src/boards/330.c
    ${FCEUMM_DIR}/src/boards/334.c
    ${FCEUMM_DIR}/src/boards/34.c
    ${FCEUMM_DIR}/src/boards/340.c
    ${FCEUMM_DIR}/src/boards/341.c
    ${FCEUMM_DIR}/src/boards/343.c
    ${FCEUMM_DIR}/src/boards/351.c
    ${FCEUMM_DIR}/src/boards/352.c
    ${FCEUMM_DIR}/src/boards/353.c
    ${FCEUMM_DIR}/src/boards/354.c
    ${FCEUMM_DIR}/src/boards/355.c
    ${FCEUMM_DIR}/src/boards/356.c
    ${FCEUMM_DIR}/src/boards/357.c
    ${FCEUMM_DIR}/src/boards/359.c
    ${FCEUMM_DIR}/src/boards/360.c
    ${FCEUMM_DIR}/src/boards/361.c
    ${FCEUMM_DIR}/src/boards/362.c
    ${FCEUMM_DIR}/src/boards/363.c
    ${FCEUMM_DIR}/src/boards/364.c
    ${FCEUMM_DIR}/src/boards/366.c
    ${FCEUMM_DIR}/src/boards/368.c
    ${FCEUMM_DIR}/src/boards/369.c
    ${FCEUMM_DIR}/src/boards/370.c
    ${FCEUMM_DIR}/src/boards/372.c
    ${FCEUMM_DIR}/src/boards/375.c
    ${FCEUMM_DIR}/src/boards/376.c
    ${FCEUMM_DIR}/src/boards/377.c
    ${FCEUMM_DIR}/src/boards/378.c
    ${FCEUMM_DIR}/src/boards/379.c
    ${FCEUMM_DIR}/src/boards/380.c
    ${FCEUMM_DIR}/src/boards/382.c
    ${FCEUMM_DIR}/src/boards/383.c
    ${FCEUMM_DIR}/src/boards/384.c
    ${FCEUMM_DIR}/src/boards/389.c
    ${FCEUMM_DIR}/src/boards/390.c
    ${FCEUMM_DIR}/src/boards/391.c
    ${FCEUMM_DIR}/src/boards/393.c
    ${FCEUMM_DIR}/src/boards/395.c
    ${FCEUMM_DIR}/src/boards/396.c
    ${FCEUMM_DIR}/src/boards/398.c
    ${FCEUMM_DIR}/src/boards/399.c
    ${FCEUMM_DIR}/src/boards/40.c
    ${FCEUMM_DIR}/src/boards/400.c
    ${FCEUMM_DIR}/src/boards/401.c
    ${FCEUMM_DIR}/src/boards/403.c
    ${FCEUMM_DIR}/src/boards/406.c
    ${FCEUMM_DIR}/src/boards/41.c
    ${FCEUMM_DIR}/src/boards/410.c
    ${FCEUMM_DIR}/src/boards/411.c
    ${FCEUMM_DIR}/src/boards/411120-c.c
    ${FCEUMM_DIR}/src/boards/412.c
    ${FCEUMM_DIR}/src/boards/413.c
    ${FCEUMM_DIR}/src/boards/414.c
    ${FCEUMM_DIR}/src/boards/416.c
    ${FCEUMM_DIR}/src/boards/417.c
    ${FCEUMM_DIR}/src/boards/418.c
    ${FCEUMM_DIR}/src/boards/42.c
    ${FCEUMM_DIR}/src/boards/420.c
    ${FCEUMM_DIR}/src/boards/428.c
    ${FCEUMM_DIR}/src/boards/43.c
    ${FCEUMM_DIR}/src/boards/430.c
    ${FCEUMM_DIR}/src/boards/431.c
    ${FCEUMM_DIR}/src/boards/432.c
    ${FCEUMM_DIR}/src/boards/433.c
    ${FCEUMM_DIR}/src/boards/434.c
    ${FCEUMM_DIR}/src/boards/437.c
    ${FCEUMM_DIR}/src/boards/438.c
    ${FCEUMM_DIR}/src/boards/439.c
    ${FCEUMM_DIR}/src/boards/441.c
    ${FCEUMM_DIR}/src/boards/443.c
    ${FCEUMM_DIR}/src/boards/444.c
    ${FCEUMM_DIR}/src/boards/445.c
    ${FCEUMM_DIR}/src/boards/446.c
    ${FCEUMM_DIR}/src/boards/447.c
    ${FCEUMM_DIR}/src/boards/448.c
    ${FCEUMM_DIR}/src/boards/449.c
    ${FCEUMM_DIR}/src/boards/450.c
    ${FCEUMM_DIR}/src/boards/451.c
    ${FCEUMM_DIR}/src/boards/452.c
    ${FCEUMM_DIR}/src/boards/453.c
    ${FCEUMM_DIR}/src/boards/454.c
    ${FCEUMM_DIR}/src/boards/455.c
    ${FCEUMM_DIR}/src/boards/456.c
    ${FCEUMM_DIR}/src/boards/457.c
    ${FCEUMM_DIR}/src/boards/458.c
    ${FCEUMM_DIR}/src/boards/46.c
    ${FCEUMM_DIR}/src/boards/460.c
    ${FCEUMM_DIR}/src/boards/461.c
    ${FCEUMM_DIR}/src/boards/463.c
    ${FCEUMM_DIR}/src/boards/465.c
    ${FCEUMM_DIR}/src/boards/466.c
    ${FCEUMM_DIR}/src/boards/467.c
    ${FCEUMM_DIR}/src/boards/468.c
    ${FCEUMM_DIR}/src/boards/471.c
    ${FCEUMM_DIR}/src/boards/473.c
    ${FCEUMM_DIR}/src/boards/474.c
    ${FCEUMM_DIR}/src/boards/475.c
    ${FCEUMM_DIR}/src/boards/476.c
    ${FCEUMM_DIR}/src/boards/478.c
    ${FCEUMM_DIR}/src/boards/480.c
    ${FCEUMM_DIR}/src/boards/482.c
    ${FCEUMM_DIR}/src/boards/483.c
    ${FCEUMM_DIR}/src/boards/484.c
    ${FCEUMM_DIR}/src/boards/485.c
    ${FCEUMM_DIR}/src/boards/487.c
    ${FCEUMM_DIR}/src/boards/489.c
    ${FCEUMM_DIR}/src/boards/490.c
    ${FCEUMM_DIR}/src/boards/491.c
    ${FCEUMM_DIR}/src/boards/492.c
    ${FCEUMM_DIR}/src/boards/493.c
    ${FCEUMM_DIR}/src/boards/494.c
    ${FCEUMM_DIR}/src/boards/495.c
    ${FCEUMM_DIR}/src/boards/498.c
    ${FCEUMM_DIR}/src/boards/499.c
    ${FCEUMM_DIR}/src/boards/50.c
    ${FCEUMM_DIR}/src/boards/500.c
    ${FCEUMM_DIR}/src/boards/501.c
    ${FCEUMM_DIR}/src/boards/502.c
    ${FCEUMM_DIR}/src/boards/503.c
    ${FCEUMM_DIR}/src/boards/504.c
    ${FCEUMM_DIR}/src/boards/505.c
    ${FCEUMM_DIR}/src/boards/506.c
    ${FCEUMM_DIR}/src/boards/507.c
    ${FCEUMM_DIR}/src/boards/508.c
    ${FCEUMM_DIR}/src/boards/509.c
    ${FCEUMM_DIR}/src/boards/51.c
    ${FCEUMM_DIR}/src/boards/510.c
    ${FCEUMM_DIR}/src/boards/511.c
    ${FCEUMM_DIR}/src/boards/512.c
    ${FCEUMM_DIR}/src/boards/514.c
    ${FCEUMM_DIR}/src/boards/516.c
    ${FCEUMM_DIR}/src/boards/518.c
    ${FCEUMM_DIR}/src/boards/520.c
    ${FCEUMM_DIR}/src/boards/524.c
    ${FCEUMM_DIR}/src/boards/525.c
    ${FCEUMM_DIR}/src/boards/527.c
    ${FCEUMM_DIR}/src/boards/528.c
    ${FCEUMM_DIR}/src/boards/529.c
    ${FCEUMM_DIR}/src/boards/530.c
    ${FCEUMM_DIR}/src/boards/533.c
    ${FCEUMM_DIR}/src/boards/536.c
    ${FCEUMM_DIR}/src/boards/537.c
    ${FCEUMM_DIR}/src/boards/539.c
    ${FCEUMM_DIR}/src/boards/542.c
    ${FCEUMM_DIR}/src/boards/544.c
    ${FCEUMM_DIR}/src/boards/545.c
    ${FCEUMM_DIR}/src/boards/546.c
    ${FCEUMM_DIR}/src/boards/548.c
    ${FCEUMM_DIR}/src/boards/549.c
    ${FCEUMM_DIR}/src/boards/554.c
    ${FCEUMM_DIR}/src/boards/556.c
    ${FCEUMM_DIR}/src/boards/557.c
    ${FCEUMM_DIR}/src/boards/558.c
    ${FCEUMM_DIR}/src/boards/559.c
    ${FCEUMM_DIR}/src/boards/563.c
    ${FCEUMM_DIR}/src/boards/564.c
    ${FCEUMM_DIR}/src/boards/565.c
    ${FCEUMM_DIR}/src/boards/566.c
    ${FCEUMM_DIR}/src/boards/567.c
    ${FCEUMM_DIR}/src/boards/568.c
    ${FCEUMM_DIR}/src/boards/569.c
    ${FCEUMM_DIR}/src/boards/57.c
    ${FCEUMM_DIR}/src/boards/570.c
    ${FCEUMM_DIR}/src/boards/571.c
    ${FCEUMM_DIR}/src/boards/572.c
    ${FCEUMM_DIR}/src/boards/573.c
    ${FCEUMM_DIR}/src/boards/574.c
    ${FCEUMM_DIR}/src/boards/575.c
    ${FCEUMM_DIR}/src/boards/576.c
    ${FCEUMM_DIR}/src/boards/577.c
    ${FCEUMM_DIR}/src/boards/578.c
    ${FCEUMM_DIR}/src/boards/579.c
    ${FCEUMM_DIR}/src/boards/580.c
    ${FCEUMM_DIR}/src/boards/581.c
    ${FCEUMM_DIR}/src/boards/582.c
    ${FCEUMM_DIR}/src/boards/583.c
    ${FCEUMM_DIR}/src/boards/584.c
    ${FCEUMM_DIR}/src/boards/585.c
    ${FCEUMM_DIR}/src/boards/586.c
    ${FCEUMM_DIR}/src/boards/587.c
    ${FCEUMM_DIR}/src/boards/588.c
    ${FCEUMM_DIR}/src/boards/589.c
    ${FCEUMM_DIR}/src/boards/590.c
    ${FCEUMM_DIR}/src/boards/591.c
    ${FCEUMM_DIR}/src/boards/592.c
    ${FCEUMM_DIR}/src/boards/594.c
    ${FCEUMM_DIR}/src/boards/595.c
    ${FCEUMM_DIR}/src/boards/596.c
    ${FCEUMM_DIR}/src/boards/597.c
    ${FCEUMM_DIR}/src/boards/598.c
    ${FCEUMM_DIR}/src/boards/599.c
    ${FCEUMM_DIR}/src/boards/6_8_12_17_561_562.c
    ${FCEUMM_DIR}/src/boards/60.c
    ${FCEUMM_DIR}/src/boards/603-5052.c
    ${FCEUMM_DIR}/src/boards/603.c
    ${FCEUMM_DIR}/src/boards/605.c
    ${FCEUMM_DIR}/src/boards/606.c
    ${FCEUMM_DIR}/src/boards/607.c
    ${FCEUMM_DIR}/src/boards/608.c
    ${FCEUMM_DIR}/src/boards/609.c
    ${FCEUMM_DIR}/src/boards/610.c
    ${FCEUMM_DIR}/src/boards/611.c
    ${FCEUMM_DIR}/src/boards/612.c
    ${FCEUMM_DIR}/src/boards/613.c
    ${FCEUMM_DIR}/src/boards/614.c
    ${FCEUMM_DIR}/src/boards/615.c
    ${FCEUMM_DIR}/src/boards/616.c
    ${FCEUMM_DIR}/src/boards/617.c
    ${FCEUMM_DIR}/src/boards/618.c
    ${FCEUMM_DIR}/src/boards/619.c
    ${FCEUMM_DIR}/src/boards/62.c
    ${FCEUMM_DIR}/src/boards/620.c
    ${FCEUMM_DIR}/src/boards/621.c
    ${FCEUMM_DIR}/src/boards/622.c
    ${FCEUMM_DIR}/src/boards/623.c
    ${FCEUMM_DIR}/src/boards/624.c
    ${FCEUMM_DIR}/src/boards/625.c
    ${FCEUMM_DIR}/src/boards/65.c
    ${FCEUMM_DIR}/src/boards/67.c
    ${FCEUMM_DIR}/src/boards/68.c
    ${FCEUMM_DIR}/src/boards/69.c
    ${FCEUMM_DIR}/src/boards/71.c
    ${FCEUMM_DIR}/src/boards/72.c
    ${FCEUMM_DIR}/src/boards/77.c
    ${FCEUMM_DIR}/src/boards/79.c
    ${FCEUMM_DIR}/src/boards/80.c
    ${FCEUMM_DIR}/src/boards/81.c
    ${FCEUMM_DIR}/src/boards/82_552.c
    ${FCEUMM_DIR}/src/boards/8237.c
    ${FCEUMM_DIR}/src/boards/83_264.c
    ${FCEUMM_DIR}/src/boards/830118C.c
    ${FCEUMM_DIR}/src/boards/830134C.c
    ${FCEUMM_DIR}/src/boards/88.c
    ${FCEUMM_DIR}/src/boards/8in1.c
    ${FCEUMM_DIR}/src/boards/91.c
    ${FCEUMM_DIR}/src/boards/96.c
    ${FCEUMM_DIR}/src/boards/99.c
    ${FCEUMM_DIR}/src/boards/a9746.c
    ${FCEUMM_DIR}/src/boards/ac-08.c
    ${FCEUMM_DIR}/src/boards/addrlatch.c
    ${FCEUMM_DIR}/src/boards/asic_fme7.c
    ${FCEUMM_DIR}/src/boards/asic_h3001.c
    ${FCEUMM_DIR}/src/boards/asic_latch.c
    ${FCEUMM_DIR}/src/boards/asic_mmc1.c
    ${FCEUMM_DIR}/src/boards/asic_mmc2and4.c
    ${FCEUMM_DIR}/src/boards/asic_mmc3.c
    ${FCEUMM_DIR}/src/boards/asic_n118.c
    ${FCEUMM_DIR}/src/boards/asic_pt8154.c
    ${FCEUMM_DIR}/src/boards/asic_qj.c
    ${FCEUMM_DIR}/src/boards/asic_tc3294.c
    ${FCEUMM_DIR}/src/boards/asic_vrc1.c
    ${FCEUMM_DIR}/src/boards/asic_vrc2and4.c
    ${FCEUMM_DIR}/src/boards/asic_vrc3.c
    ${FCEUMM_DIR}/src/boards/asic_vrc6.c
    ${FCEUMM_DIR}/src/boards/asic_vrc7.c
    ${FCEUMM_DIR}/src/boards/bandai.c
    ${FCEUMM_DIR}/src/boards/bb.c
    ${FCEUMM_DIR}/src/boards/bj56.c
    ${FCEUMM_DIR}/src/boards/bmc42in1r.c
    ${FCEUMM_DIR}/src/boards/bmc60311c.c
    ${FCEUMM_DIR}/src/boards/bmc64in1nr.c
    ${FCEUMM_DIR}/src/boards/bmc80013b.c
    ${FCEUMM_DIR}/src/boards/bmc830425C4391t.c
    ${FCEUMM_DIR}/src/boards/bmcctc09.c
    ${FCEUMM_DIR}/src/boards/bmcgamecard.c
    ${FCEUMM_DIR}/src/boards/bmck3006.c
    ${FCEUMM_DIR}/src/boards/bmck3033.c
    ${FCEUMM_DIR}/src/boards/bmcl6in1.c
    ${FCEUMM_DIR}/src/boards/BMW8544.c
    ${FCEUMM_DIR}/src/boards/bonza.c
    ${FCEUMM_DIR}/src/boards/bs-5.c
    ${FCEUMM_DIR}/src/boards/cartram.c
    ${FCEUMM_DIR}/src/boards/cheapocabra.c
    ${FCEUMM_DIR}/src/boards/coolgirl.c
    ${FCEUMM_DIR}/src/boards/datalatch.c
    ${FCEUMM_DIR}/src/boards/dream.c
    ${FCEUMM_DIR}/src/boards/edu2000.c
    ${FCEUMM_DIR}/src/boards/eeprom_93Cx6.c
    ${FCEUMM_DIR}/src/boards/eh8813a.c
    ${FCEUMM_DIR}/src/boards/emu2413.c
    ${FCEUMM_DIR}/src/boards/et-100.c
    ${FCEUMM_DIR}/src/boards/et-4320.c
    ${FCEUMM_DIR}/src/boards/f-15.c
    ${FCEUMM_DIR}/src/boards/famicombox.c
    ${FCEUMM_DIR}/src/boards/faridunrom.c
    ${FCEUMM_DIR}/src/boards/fifo.c
    ${FCEUMM_DIR}/src/boards/fk23c.c
    ${FCEUMM_DIR}/src/boards/flashrom.c
    ${FCEUMM_DIR}/src/boards/gn26.c
    ${FCEUMM_DIR}/src/boards/h2288.c
    ${FCEUMM_DIR}/src/boards/hp10xx_hp20xx.c
    ${FCEUMM_DIR}/src/boards/hp898f.c
    ${FCEUMM_DIR}/src/boards/inx007t.c
    ${FCEUMM_DIR}/src/boards/jyasic.c
    ${FCEUMM_DIR}/src/boards/karaoke.c
    ${FCEUMM_DIR}/src/boards/KG256.c
    ${FCEUMM_DIR}/src/boards/kof97.c
    ${FCEUMM_DIR}/src/boards/KS7012.c
    ${FCEUMM_DIR}/src/boards/KS7013.c
    ${FCEUMM_DIR}/src/boards/KS7016.c
    ${FCEUMM_DIR}/src/boards/KS7017.c
    ${FCEUMM_DIR}/src/boards/KS7030.c
    ${FCEUMM_DIR}/src/boards/KS7031.c
    ${FCEUMM_DIR}/src/boards/KS7032.c
    ${FCEUMM_DIR}/src/boards/KS7037.c
    ${FCEUMM_DIR}/src/boards/KS7057.c
    ${FCEUMM_DIR}/src/boards/latch.c
    ${FCEUMM_DIR}/src/boards/le05.c
    ${FCEUMM_DIR}/src/boards/lh32.c
    ${FCEUMM_DIR}/src/boards/lh51.c
    ${FCEUMM_DIR}/src/boards/lh53.c
    ${FCEUMM_DIR}/src/boards/malee.c
    ${FCEUMM_DIR}/src/boards/mihunche.c
    ${FCEUMM_DIR}/src/boards/mmc1.c
    ${FCEUMM_DIR}/src/boards/mmc2and4.c
    ${FCEUMM_DIR}/src/boards/mmc3.c
    ${FCEUMM_DIR}/src/boards/mmc5.c
    ${FCEUMM_DIR}/src/boards/msm6585.c
    ${FCEUMM_DIR}/src/boards/n106.c
    ${FCEUMM_DIR}/src/boards/n625092.c
    ${FCEUMM_DIR}/src/boards/novel.c
    ${FCEUMM_DIR}/src/boards/onebus.c
    ${FCEUMM_DIR}/src/boards/pec-586.c
    ${FCEUMM_DIR}/src/boards/pic16c5x.c
    ${FCEUMM_DIR}/src/boards/resetnromxin1.c
    ${FCEUMM_DIR}/src/boards/resettxrom.c
    ${FCEUMM_DIR}/src/boards/rt-01.c
    ${FCEUMM_DIR}/src/boards/SA-9602B.c
    ${FCEUMM_DIR}/src/boards/sachen.c
    ${FCEUMM_DIR}/src/boards/sheroes.c
    ${FCEUMM_DIR}/src/boards/subor.c
    ${FCEUMM_DIR}/src/boards/super40in1.c
    ${FCEUMM_DIR}/src/boards/supervision.c
    ${FCEUMM_DIR}/src/boards/t-227-1.c
    ${FCEUMM_DIR}/src/boards/t-262.c
    ${FCEUMM_DIR}/src/boards/tengen.c
    ${FCEUMM_DIR}/src/boards/transformer.c
    ${FCEUMM_DIR}/src/boards/txcchip.c
    ${FCEUMM_DIR}/src/boards/unrom512.c
    ${FCEUMM_DIR}/src/boards/vrc1.c
    ${FCEUMM_DIR}/src/boards/vrc3.c
    ${FCEUMM_DIR}/src/boards/vrc6.c
    ${FCEUMM_DIR}/src/boards/vrc7.c
    ${FCEUMM_DIR}/src/boards/vrc7p.c
    ${FCEUMM_DIR}/src/boards/vrcirq.c
    ${FCEUMM_DIR}/src/cart.c
    ${FCEUMM_DIR}/src/cheat.c
    ${FCEUMM_DIR}/src/crc32.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro_dipswitch.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/compat/compat_posix_string.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/compat/compat_snprintf.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/compat/compat_strcasestr.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/compat/compat_strl.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/compat/fopen_utf8.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/encodings/encoding_deflate.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/encodings/encoding_utf.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/file/file_path_io.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/file/file_path.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/dds/rdds.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/png/rpng.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/vorbis/rvorbis.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/vp8/rvp8.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/wav/rwav.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/formats/webp/rwebp.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/file_stream_transforms.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/file_stream.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/memory_stream.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/trans_stream_deflate.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/trans_stream_pipe.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/streams/trans_stream.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/string/stdstring.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/time/rtime.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/vfs/vfs_implementation.c
    ${FCEUMM_DIR}/src/drivers/libretro/libretro.c
    ${FCEUMM_DIR}/src/fceu-endian.c
    ${FCEUMM_DIR}/src/fceu-memory.c
    ${FCEUMM_DIR}/src/fceu.c
    ${FCEUMM_DIR}/src/fds_apu.c
    ${FCEUMM_DIR}/src/fds.c
    ${FCEUMM_DIR}/src/file.c
    ${FCEUMM_DIR}/src/filter.c
    ${FCEUMM_DIR}/src/general.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_audio.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_image.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_load.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_patch.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_ppu.c
    ${FCEUMM_DIR}/src/hdpack/hdpack_render.c
    ${FCEUMM_DIR}/src/ines.c
    ${FCEUMM_DIR}/src/input.c
    ${FCEUMM_DIR}/src/input/arkanoid.c
    ${FCEUMM_DIR}/src/input/bbox.c
    ${FCEUMM_DIR}/src/input/bworld.c
    ${FCEUMM_DIR}/src/input/cursor.c
    ${FCEUMM_DIR}/src/input/fkb.c
    ${FCEUMM_DIR}/src/input/ftrainer.c
    ${FCEUMM_DIR}/src/input/hypershot.c
    ${FCEUMM_DIR}/src/input/mahjong.c
    ${FCEUMM_DIR}/src/input/mouse.c
    ${FCEUMM_DIR}/src/input/oekakids.c
    ${FCEUMM_DIR}/src/input/pec586kb.c
    ${FCEUMM_DIR}/src/input/powerpad.c
    ${FCEUMM_DIR}/src/input/quiz.c
    ${FCEUMM_DIR}/src/input/shadow.c
    ${FCEUMM_DIR}/src/input/suborkb.c
    ${FCEUMM_DIR}/src/input/toprider.c
    ${FCEUMM_DIR}/src/input/zapper.c
    ${FCEUMM_DIR}/src/md5.c
    ${FCEUMM_DIR}/src/nsf.c
    ${FCEUMM_DIR}/src/ntsc/nes_ntsc.c
    ${FCEUMM_DIR}/src/palette.c
    ${FCEUMM_DIR}/src/ppu.c
    ${FCEUMM_DIR}/src/sound.c
    ${FCEUMM_DIR}/src/state.c
    ${FCEUMM_DIR}/src/unif.c
    ${FCEUMM_DIR}/src/video.c
    ${FCEUMM_DIR}/src/vsuni.c
    ${FCEUMM_DIR}/src/x6502.c
)

target_include_directories(fceumm_core SYSTEM PRIVATE
    ${FCEUMM_DIR}/src/drivers/libretro
    ${FCEUMM_DIR}/src/drivers/libretro/libretro-common/include
    ${FCEUMM_DIR}/src
    ${FCEUMM_DIR}/src/input
    ${FCEUMM_DIR}/src/boards
    ${FCEUMM_DIR}/src/ntsc
)

target_compile_definitions(fceumm_core PRIVATE
    __LIBRETRO__
    PATH_MAX=1024
    FCEU_VERSION_NUMERIC=9900
    FRONTEND_SUPPORTS_RGB888
    HAVE_NTSC_FILTER
    HAVE_HDPACK
    PSS_STYLE=1
    GIT_VERSION=\"b5e3566\"
)

target_compile_options(fceumm_core PRIVATE -Wno-write-strings -Wsign-compare -Wundef -Wmissing-prototypes)

# Vendored third-party source: not held to this project's own -Wall -Wextra
# (matches sameboy_core/genesis_plus_gx_core), linked with upstream's own
# version script so only the standard retro_* Libretro ABI is exported.
# GNU-only linker flags (Linux per-core gate); Apple ld does not support them.
if(NOT APPLE)
target_link_options(fceumm_core PRIVATE
    "-Wl,--version-script=${FCEUMM_DIR}/src/drivers/libretro/link.T"
    "-Wl,--no-undefined"
)
endif()

target_link_libraries(fceumm_core
    m
)
