# Stella (Atari 2600): exact shared C++ source inventory for the vendored
# upstream 7.0 libretro Android build. All Android, Linux, and Windows
# fragments include this file to prevent platform source drift. The including
# project must set STELLA_DIR to third_party/cores/stella first.

if(NOT DEFINED STELLA_DIR OR NOT IS_DIRECTORY "${STELLA_DIR}")
    message(FATAL_ERROR
        "stella-sources.cmake: STELLA_DIR must name the vendored core tree")
endif()

set(ROMM_STELLA_SOURCES
    ${STELLA_DIR}/os/libretro/libretro.cxx
    ${STELLA_DIR}/os/libretro/FSNodeLIBRETRO.cxx
    ${STELLA_DIR}/os/libretro/StellaLIBRETRO.cxx
    ${STELLA_DIR}/common/AudioQueue.cxx
    ${STELLA_DIR}/common/AudioSettings.cxx
    ${STELLA_DIR}/common/Base.cxx
    ${STELLA_DIR}/common/Bezel.cxx
    ${STELLA_DIR}/common/DevSettingsHandler.cxx
    ${STELLA_DIR}/common/FpsMeter.cxx
    ${STELLA_DIR}/common/FSNodeZIP.cxx
    ${STELLA_DIR}/common/JoyMap.cxx
    ${STELLA_DIR}/common/KeyMap.cxx
    ${STELLA_DIR}/common/Logger.cxx
    ${STELLA_DIR}/common/MouseControl.cxx
    ${STELLA_DIR}/common/PaletteHandler.cxx
    ${STELLA_DIR}/common/PhosphorHandler.cxx
    ${STELLA_DIR}/common/PhysicalJoystick.cxx
    ${STELLA_DIR}/common/PJoystickHandler.cxx
    ${STELLA_DIR}/common/PKeyboardHandler.cxx
    ${STELLA_DIR}/common/RewindManager.cxx
    ${STELLA_DIR}/common/StaggeredLogger.cxx
    ${STELLA_DIR}/common/StateManager.cxx
    ${STELLA_DIR}/common/TimerManager.cxx
    ${STELLA_DIR}/common/VideoModeHandler.cxx
    ${STELLA_DIR}/common/tv_filters/AtariNTSC.cxx
    ${STELLA_DIR}/common/tv_filters/NTSCFilter.cxx
    ${STELLA_DIR}/common/repository/CompositeKeyValueRepository.cxx
    ${STELLA_DIR}/common/repository/CompositeKVRJsonAdapter.cxx
    ${STELLA_DIR}/common/repository/KeyValueRepositoryConfigfile.cxx
    ${STELLA_DIR}/common/repository/KeyValueRepositoryJsonFile.cxx
    ${STELLA_DIR}/common/repository/KeyValueRepositoryPropertyFile.cxx
    ${STELLA_DIR}/emucore/AtariVox.cxx
    ${STELLA_DIR}/emucore/Bankswitch.cxx
    ${STELLA_DIR}/emucore/Booster.cxx
    ${STELLA_DIR}/emucore/Cart.cxx
    ${STELLA_DIR}/emucore/CartCreator.cxx
    ${STELLA_DIR}/emucore/CartDetector.cxx
    ${STELLA_DIR}/emucore/CartEnhanced.cxx
    ${STELLA_DIR}/emucore/Cart03E0.cxx
    ${STELLA_DIR}/emucore/Cart0840.cxx
    ${STELLA_DIR}/emucore/Cart0FA0.cxx
    ${STELLA_DIR}/emucore/Cart2K.cxx
    ${STELLA_DIR}/emucore/Cart3E.cxx
    ${STELLA_DIR}/emucore/Cart3EPlus.cxx
    ${STELLA_DIR}/emucore/Cart3EX.cxx
    ${STELLA_DIR}/emucore/Cart3F.cxx
    ${STELLA_DIR}/emucore/Cart4A50.cxx
    ${STELLA_DIR}/emucore/Cart4K.cxx
    ${STELLA_DIR}/emucore/Cart4KSC.cxx
    ${STELLA_DIR}/emucore/CartAR.cxx
    ${STELLA_DIR}/emucore/CartARM.cxx
    ${STELLA_DIR}/emucore/CartBF.cxx
    ${STELLA_DIR}/emucore/CartBFSC.cxx
    ${STELLA_DIR}/emucore/CartBUS.cxx
    ${STELLA_DIR}/emucore/CartCDF.cxx
    ${STELLA_DIR}/emucore/CartCM.cxx
    ${STELLA_DIR}/emucore/CartCTY.cxx
    ${STELLA_DIR}/emucore/CartCV.cxx
    ${STELLA_DIR}/emucore/CartDF.cxx
    ${STELLA_DIR}/emucore/CartDFSC.cxx
    ${STELLA_DIR}/emucore/CartDPC.cxx
    ${STELLA_DIR}/emucore/CartDPCPlus.cxx
    ${STELLA_DIR}/emucore/CartE0.cxx
    ${STELLA_DIR}/emucore/CartE7.cxx
    ${STELLA_DIR}/emucore/CartEF.cxx
    ${STELLA_DIR}/emucore/CartEFSC.cxx
    ${STELLA_DIR}/emucore/CartELF.cxx
    ${STELLA_DIR}/emucore/CartF0.cxx
    ${STELLA_DIR}/emucore/CartF4.cxx
    ${STELLA_DIR}/emucore/CartF4SC.cxx
    ${STELLA_DIR}/emucore/CartF6.cxx
    ${STELLA_DIR}/emucore/CartF6SC.cxx
    ${STELLA_DIR}/emucore/CartF8.cxx
    ${STELLA_DIR}/emucore/CartF8SC.cxx
    ${STELLA_DIR}/emucore/CartFA2.cxx
    ${STELLA_DIR}/emucore/CartFA.cxx
    ${STELLA_DIR}/emucore/CartFC.cxx
    ${STELLA_DIR}/emucore/CartFE.cxx
    ${STELLA_DIR}/emucore/CartGL.cxx
    ${STELLA_DIR}/emucore/CartJANE.cxx
    ${STELLA_DIR}/emucore/CartMDM.cxx
    ${STELLA_DIR}/emucore/CartMVC.cxx
    ${STELLA_DIR}/emucore/CartSB.cxx
    ${STELLA_DIR}/emucore/CartTVBoy.cxx
    ${STELLA_DIR}/emucore/CartUA.cxx
    ${STELLA_DIR}/emucore/CartWD.cxx
    ${STELLA_DIR}/emucore/CartWF8.cxx
    ${STELLA_DIR}/emucore/CartX07.cxx
    ${STELLA_DIR}/emucore/CompuMate.cxx
    ${STELLA_DIR}/emucore/Console.cxx
    ${STELLA_DIR}/emucore/Control.cxx
    ${STELLA_DIR}/emucore/ControllerDetector.cxx
    ${STELLA_DIR}/emucore/CortexM0.cxx
    ${STELLA_DIR}/emucore/DispatchResult.cxx
    ${STELLA_DIR}/emucore/Driving.cxx
    ${STELLA_DIR}/emucore/EmulationTiming.cxx
    ${STELLA_DIR}/emucore/EmulationWorker.cxx
    ${STELLA_DIR}/emucore/EventHandler.cxx
    ${STELLA_DIR}/emucore/FBSurface.cxx
    ${STELLA_DIR}/emucore/FrameBuffer.cxx
    ${STELLA_DIR}/emucore/FSNode.cxx
    ${STELLA_DIR}/emucore/Genesis.cxx
    ${STELLA_DIR}/emucore/GlobalKeyHandler.cxx
    ${STELLA_DIR}/emucore/Joy2BPlus.cxx
    ${STELLA_DIR}/emucore/Joystick.cxx
    ${STELLA_DIR}/emucore/Keyboard.cxx
    ${STELLA_DIR}/emucore/KidVid.cxx
    ${STELLA_DIR}/emucore/Lightgun.cxx
    ${STELLA_DIR}/emucore/M6502.cxx
    ${STELLA_DIR}/emucore/M6532.cxx
    ${STELLA_DIR}/emucore/MD5.cxx
    ${STELLA_DIR}/emucore/MindLink.cxx
    ${STELLA_DIR}/emucore/MT24LC256.cxx
    ${STELLA_DIR}/emucore/OSystem.cxx
    ${STELLA_DIR}/emucore/Paddles.cxx
    ${STELLA_DIR}/emucore/PlusROM.cxx
    ${STELLA_DIR}/emucore/PointingDevice.cxx
    ${STELLA_DIR}/emucore/Props.cxx
    ${STELLA_DIR}/emucore/PropsSet.cxx
    ${STELLA_DIR}/emucore/QuadTari.cxx
    ${STELLA_DIR}/emucore/SaveKey.cxx
    ${STELLA_DIR}/emucore/Serializer.cxx
    ${STELLA_DIR}/emucore/Settings.cxx
    ${STELLA_DIR}/emucore/Switches.cxx
    ${STELLA_DIR}/emucore/System.cxx
    ${STELLA_DIR}/emucore/Thumbulator.cxx
    ${STELLA_DIR}/emucore/elf/BusTransactionQueue.cxx
    ${STELLA_DIR}/emucore/elf/ElfEnvironment.cxx
    ${STELLA_DIR}/emucore/elf/ElfLinker.cxx
    ${STELLA_DIR}/emucore/elf/ElfParser.cxx
    ${STELLA_DIR}/emucore/elf/ElfUtil.cxx
    ${STELLA_DIR}/emucore/elf/VcsLib.cxx
    ${STELLA_DIR}/emucore/tia/AudioChannel.cxx
    ${STELLA_DIR}/emucore/tia/Audio.cxx
    ${STELLA_DIR}/emucore/tia/Background.cxx
    ${STELLA_DIR}/emucore/tia/Ball.cxx
    ${STELLA_DIR}/emucore/tia/DrawCounterDecodes.cxx
    ${STELLA_DIR}/emucore/tia/frame-manager/AbstractFrameManager.cxx
    ${STELLA_DIR}/emucore/tia/frame-manager/FrameLayoutDetector.cxx
    ${STELLA_DIR}/emucore/tia/frame-manager/FrameManager.cxx
    ${STELLA_DIR}/emucore/tia/frame-manager/JitterEmulation.cxx
    ${STELLA_DIR}/emucore/tia/LatchedInput.cxx
    ${STELLA_DIR}/emucore/tia/Missile.cxx
    ${STELLA_DIR}/emucore/tia/AnalogReadout.cxx
    ${STELLA_DIR}/emucore/tia/Player.cxx
    ${STELLA_DIR}/emucore/tia/Playfield.cxx
    ${STELLA_DIR}/emucore/TIASurface.cxx
    ${STELLA_DIR}/emucore/tia/TIA.cxx
)

list(LENGTH ROMM_STELLA_SOURCES ROMM_STELLA_SOURCE_COUNT)
if(NOT ROMM_STELLA_SOURCE_COUNT EQUAL 148)
    message(FATAL_ERROR
        "stella-sources.cmake: expected exactly 148 sources, found "
        "${ROMM_STELLA_SOURCE_COUNT} — the shared source list drifted")
endif()
foreach(_romm_stella_src IN LISTS ROMM_STELLA_SOURCES)
    if(NOT EXISTS "${_romm_stella_src}")
        message(FATAL_ERROR
            "stella-sources.cmake: missing vendored source: "
            "${_romm_stella_src}")
    endif()
endforeach()
