// test_windows_process_control.cpp — Windows-specific native coverage for
// the Win32 process-control slice (Phase 2, plans/WINDOWS_IMPL.md section
// 5.1): the console-control-handler seam and the teardown watchdog,
// compiled directly from windows_process_control.cpp alongside this test
// (self-contained, like test_windows_dynamic_library — created only on
// WIN32; the POSIX host suite keeps its existing selection untouched).
//
// Coverage:
//   - control-handler SEAM: the pure classification in control_events.h
//     (CTRL_C/BREAK/CLOSE/SHUTDOWN terminate; CTRL_LOGOFF and unknown values
//     do not), plus a live GenerateConsoleCtrlEvent(CTRL_C/CTRL_BREAK) to
//     this process's own PID when a console is attached — proving the
//     installed handler flips terminationRequested() without killing us.
//     (CLOSE/SHUTDOWN cannot be generated by GenerateConsoleCtrlEvent; they
//     are pinned by the seam classification and the static_asserts in the
//     implementation.)
//   - watchdog DISARM before timeout, repeated arm/disarm safety, and
//     alarm(0)-style non-positive timeouts: run in a CHILD process with a
//     completion sentinel, because a misfiring watchdog would TerminateProcess
//     this one with exit code 0 (the _exit(0) contract) and ctest would see
//     a false pass — the child's sentinel makes every outcome positive.
//   - forced termination of the EXACT process: a child arms the watchdog,
//     then "deadlocks" (Sleep(INFINITE)); the parent verifies the child was
//     terminated by the watchdog at ~the requested timeout with exit code 0
//     and NO sentinel, while the parent itself keeps running to report.
//
// Bounded: every wait has an explicit cap; total runtime is a few seconds.
#include <native/player/process_control.h>
#include <native/platform/windows/control_events.h>

#include "romm_test.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

namespace {

// --- Child-process plumbing -------------------------------------------------
// The test spawns ITSELF with a mode argument; the child reports completion
// through a sentinel file (wide API throughout: temp paths may contain
// non-ASCII characters).

std::wstring sentinelPath(const wchar_t* tag) {
    wchar_t base[MAX_PATH];
    const DWORD n = GetTempPathW(MAX_PATH, base);
    if (n == 0 || n >= MAX_PATH) return L"";
    return std::wstring(base) + L"romm_pc_test_" + tag + L"_" +
           std::to_wstring(GetCurrentProcessId()) + L".sentinel";
}

bool writeSentinel(const std::wstring& path, const wchar_t* text) {
    if (path.empty()) return false;
    const HANDLE handle = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr,
                                      CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (handle == INVALID_HANDLE_VALUE) return false;
    const DWORD length = static_cast<DWORD>(wcslen(text));
    DWORD written = 0;
    const bool ok = WriteFile(handle, text, length, &written, nullptr) != 0 && written == length;
    CloseHandle(handle);
    return ok;
}

std::wstring readSentinel(const std::wstring& path) {
    if (path.empty()) return L"";
    const HANDLE handle = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr,
                                      OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (handle == INVALID_HANDLE_VALUE) return L"";
    std::vector<wchar_t> buffer(4096);
    DWORD read = 0;
    const bool ok = ReadFile(handle, buffer.data(), static_cast<DWORD>(buffer.size()), &read,
                             nullptr) != 0;
    CloseHandle(handle);
    if (!ok) return L"";
    return std::wstring(buffer.begin(), buffer.begin() + read);
}

struct ChildResult {
    bool launched = false;
    bool exited = false;
    DWORD exitCode = 0;
    std::uint64_t elapsedMs = 0;
};

// Spawns this executable with `args`, waits up to `waitLimitMs`, and — if the
// child is still alive at the cap (a watchdog that never fired) — kills it so
// no test run leaks a process. The kill uses exit code 1, distinct from both
// the clean-exit (0) and watchdog-forced-termination (0) outcomes, which the
// caller disambiguates through the sentinel + elapsed time.
ChildResult runChild(const std::wstring& args, DWORD waitLimitMs) {
    ChildResult result;
    wchar_t exePath[MAX_PATH];
    const DWORD n = GetModuleFileNameW(nullptr, exePath, MAX_PATH);
    if (n == 0 || n >= MAX_PATH) return result;
    std::wstring commandLine = L"\"" + std::wstring(exePath) + L"\"" + args;
    STARTUPINFOW si {};
    si.cb = sizeof(si);
    PROCESS_INFORMATION pi {};
    if (!CreateProcessW(nullptr, &commandLine[0], nullptr, nullptr, FALSE, 0, nullptr, nullptr,
                        &si, &pi)) {
        return result;
    }
    result.launched = true;
    const std::uint64_t start = GetTickCount64();
    const DWORD wait = WaitForSingleObject(pi.hProcess, waitLimitMs);
    if (wait != WAIT_OBJECT_0) {
        TerminateProcess(pi.hProcess, 1);  // bound the test: no leaked children
        WaitForSingleObject(pi.hProcess, 2000);
    }
    result.elapsedMs = GetTickCount64() - start;
    DWORD code = STILL_ACTIVE;
    if (GetExitCodeProcess(pi.hProcess, &code) != 0 && code != STILL_ACTIVE) {
        result.exited = true;
        result.exitCode = code;  // cap-kill carries code 1; clean and watchdog exits carry 0
    }
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return result;
}

std::wstring withSentinel(const std::wstring& path) {
    return L" \"" + path + L"\"";
}

// --- Child modes ------------------------------------------------------------
int runWatchdogCyclesChild(const std::wstring& sentinel) {
    // Repeated arm/disarm must be safe: each disarm joins its thread, so no
    // stale watchdog can fire later; a non-positive timeout cancels (POSIX
    // alarm(0)) instead of arming an immediate kill. If ANY of these misfires,
    // the process dies before the sentinel and the parent fails the test.
    romm::player::armTeardownWatchdog(1);
    Sleep(100);
    romm::player::disarmTeardownWatchdog();
    for (int i = 0; i < 4; ++i) {
        romm::player::armTeardownWatchdog(1);
        Sleep(50);
        romm::player::disarmTeardownWatchdog();
    }
    romm::player::disarmTeardownWatchdog();  // disarm when not armed: safe no-op
    romm::player::armTeardownWatchdog(0);    // alarm(0) semantics: cancel, don't kill
    Sleep(300);                              // an immediate kill would die in here
    return writeSentinel(sentinel, L"CYCLES_OK") ? 0 : 1;
}

int runWatchdogDisarmChild(const std::wstring& sentinel) {
    // Disarm BEFORE the timeout: arm for 1s, disarm at 300ms, then live well
    // past the would-be firing point and report. A broken disarm means death
    // at ~1s with no sentinel — a visible failure either way.
    romm::player::armTeardownWatchdog(1);
    Sleep(300);
    romm::player::disarmTeardownWatchdog();
    Sleep(1500);  // past the 1s deadline: survival IS the assertion
    return writeSentinel(sentinel, L"DISARM_OK") ? 0 : 1;
}

int runWatchdogDeadlockChild() {
    // Simulate core teardown deadlocking AFTER the result file was committed:
    // arm the watchdog for 2s, then block forever on the main "thread". The
    // independent watchdog must terminate THIS exact process at ~2s — no
    // sentinel is written, and the exit code is 0 (the _exit(0) contract).
    romm::player::armTeardownWatchdog(2);
    Sleep(INFINITE);
    return 1;  // unreachable: a working watchdog never lets us get here
}

// Splits GetCommandLineW() into quote-aware tokens (the sentinel path may
// contain spaces; this test never generates embedded double quotes). Token 0
// is the executable path.
std::vector<std::wstring> wideArgs() {
    std::vector<std::wstring> args;
    const wchar_t* line = GetCommandLineW();
    std::wstring current;
    bool inQuotes = false;
    bool tokenSeen = false;
    for (const wchar_t* p = line; *p != L'\0'; ++p) {
        const wchar_t c = *p;
        if (c == L'"') {
            inQuotes = !inQuotes;
            tokenSeen = true;
        } else if (c == L' ' && !inQuotes) {
            if (tokenSeen || !current.empty()) {
                args.push_back(current);
                current.clear();
                tokenSeen = false;
            }
        } else {
            current.push_back(c);
            tokenSeen = true;
        }
    }
    if (tokenSeen || !current.empty()) args.push_back(current);
    return args;
}

}  // namespace

int main() {
    using romm::win32::isTerminationControlEvent;

    // --- Child mode dispatch (the parent spawns us with one of these). ----
    const std::vector<std::wstring> args = wideArgs();
    if (args.size() == 2 && args[0] == L"--watchdog-cycles") {
        return runWatchdogCyclesChild(args[1]);
    }
    if (args.size() == 2 && args[0] == L"--watchdog-disarm") {
        return runWatchdogDisarmChild(args[1]);
    }
    if (args.size() == 1 && args[0] == L"--watchdog-deadlock") {
        return runWatchdogDeadlockChild();
    }

    // --- Parent: the console-control-handler seam. -------------------------
    // Pure classification (the fakeable seam): exactly the four termination
    // events, nothing else — logoff and unknown values fall through to the
    // system's default action.
    CHECK(isTerminationControlEvent(romm::win32::kCtrlCEvent));
    CHECK(isTerminationControlEvent(romm::win32::kCtrlBreakEvent));
    CHECK(isTerminationControlEvent(romm::win32::kCtrlCloseEvent));
    CHECK(isTerminationControlEvent(romm::win32::kCtrlShutdownEvent));
    CHECK(!isTerminationControlEvent(romm::win32::kCtrlLogoffEvent));
    CHECK(!isTerminationControlEvent(4));  // reserved value: not ours
    CHECK(!isTerminationControlEvent(7));  // unknown value: not ours

    // Install is "exactly once at startup" (contract): the flag starts false,
    // and a second call is an explicit no-op rather than a stacked handler.
    CHECK(!romm::player::terminationRequested());
    romm::player::installTerminationHandlers();
    romm::player::installTerminationHandlers();  // idempotent by contract
    CHECK(!romm::player::terminationRequested());

    // Live event delivery, when a console is attached: send CTRL_C then
    // CTRL_BREAK to THIS process's own PID only (never the whole console).
    // If the handler misclassified either as unhandled, the system default
    // action would kill this test — a loud failure, not a silent pass.
    // (CLOSE/SHUTDOWN cannot be generated by GenerateConsoleCtrlEvent; they
    // are pinned by the seam classification above plus the static_asserts in
    // windows_process_control.cpp.)
    {
        DWORD consolePids[1] = {0};
        if (GetConsoleProcessList(consolePids, 1) == 1 &&
            consolePids[0] == GetCurrentProcessId()) {
            if (GenerateConsoleCtrlEvent(CTRL_C_EVENT, GetCurrentProcessId())) {
                bool seen = false;
                for (int i = 0; i < 100 && !seen; ++i) {  // bounded: 5s max
                    Sleep(50);
                    seen = romm::player::terminationRequested();
                }
                CHECK(seen);  // the handler flipped the flag, async-safely
            }
            if (GenerateConsoleCtrlEvent(CTRL_BREAK_EVENT, GetCurrentProcessId())) {
                Sleep(200);  // reaching here at all proves BREAK was handled
                CHECK(romm::player::terminationRequested());
            }
        }
    }

    // --- Parent: the teardown watchdog, proven through child processes. ----
    // In-process arm/disarm cannot self-verify — a misfiring watchdog would
    // TerminateProcess this test with exit code 0 (the _exit(0) contract) and
    // ctest would record a false pass. The children's completion sentinels
    // make every outcome positive instead.

    const std::wstring cyclesSentinel = sentinelPath(L"cycles");
    DeleteFileW(cyclesSentinel.c_str());
    {
        // Repeated arm/disarm, disarm-when-not-armed, and alarm(0) semantics.
        const ChildResult r = runChild(L" --watchdog-cycles" + withSentinel(cyclesSentinel), 15000);
        CHECK(r.launched);
        CHECK(r.exited);
        CHECK_EQ(r.exitCode, 0u);
        CHECK(readSentinel(cyclesSentinel) == L"CYCLES_OK");
    }

    const std::wstring disarmSentinel = sentinelPath(L"disarm");
    DeleteFileW(disarmSentinel.c_str());
    {
        // Disarm BEFORE the timeout: arm 1s, disarm at 300ms, then survive
        // well past the would-be firing point and report DISARM_OK. A broken
        // disarm means death at ~1s with no sentinel and a short elapsed time.
        const ChildResult r = runChild(L" --watchdog-disarm" + withSentinel(disarmSentinel), 15000);
        CHECK(r.launched);
        CHECK(r.exited);
        CHECK_EQ(r.exitCode, 0u);
        CHECK(r.elapsedMs >= 1800);  // slept past the 1s deadline on purpose
        CHECK(readSentinel(disarmSentinel) == L"DISARM_OK");
    }

    const std::wstring deadlockSentinel = sentinelPath(L"deadlock");
    DeleteFileW(deadlockSentinel.c_str());
    {
        // Forced termination of the EXACT process: the child arms a 2s
        // watchdog, then deadlocks forever. The independent watchdog must
        // kill it at ~2s (exit code 0, no sentinel) while THIS parent keeps
        // running to report — proof the watchdog outlives a deadlocked core
        // teardown path.
        const ChildResult r = runChild(L" --watchdog-deadlock", 15000);
        CHECK(r.launched);
        CHECK(r.exited);
        CHECK_EQ(r.exitCode, 0u);  // TerminateProcess(..., 0): the _exit(0) contract
        CHECK(r.elapsedMs >= 1500);  // not before ~the requested timeout
        CHECK(r.elapsedMs <= 10000);  // and far under the wait cap: no hang
        CHECK(readSentinel(deadlockSentinel).empty());  // it never "finished"
    }

    return rommtest::finish("test_windows_process_control");
}
