package com.romm.androidtv.romm.save

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query

/**
 * Room DAO for [SaveReplicaEntity] (LIBRETRO_REFACTOR.md section 11.1).
 *
 * All queries are scoped by the same (serverKey, userKey, romId, romHash,
 * slot) tuple as the entity's unique index, or filter by [SaveSyncStatus] —
 * there is deliberately no "list everything" query with no scope, since
 * every real caller (the sync coordinator, the upload worker) always knows
 * which server/user/ROM it's acting on.
 */
@Dao
interface SaveReplicaDao {

    /**
     * Inserts a new record, or replaces the existing one for the same
     * (serverKey, userKey, romId, romHash, slot) tuple. Callers should
     * always read-modify-write via [findByScope] first when they mean to
     * update a subset of fields, since [OnConflictStrategy.REPLACE] fully
     * overwrites the row (including its autogenerated [SaveReplicaEntity.id]).
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(entity: SaveReplicaEntity): Long

    @Query(
        "SELECT * FROM save_replicas " +
            "WHERE serverKey = :serverKey AND userKey = :userKey " +
            "AND romId = :romId AND romHash = :romHash AND slot = :slot " +
            "LIMIT 1",
    )
    suspend fun findByScope(
        serverKey: String,
        userKey: String,
        romId: Long,
        romHash: String,
        slot: String,
    ): SaveReplicaEntity?

    @Query(
        "SELECT * FROM save_replicas " +
            "WHERE serverKey = :serverKey AND userKey = :userKey AND syncStatus = :status",
    )
    suspend fun findByStatus(serverKey: String, userKey: String, status: SaveSyncStatus): List<SaveReplicaEntity>

    /**
     * Records a successful server round trip only if this is still the local generation that
     * was uploaded. A newer checkpoint must never be overwritten by a stale worker completion.
     */
    @Query(
        "UPDATE save_replicas SET rommSaveId = :rommSaveId, serverHash = :serverHash, " +
            "serverSizeBytes = :serverSizeBytes, serverUpdatedAtEpochMs = :serverUpdatedAtEpochMs, " +
            "syncStatus = 'SYNCED', lastError = NULL " +
            "WHERE serverKey = :serverKey AND userKey = :userKey " +
            "AND romId = :romId AND romHash = :romHash AND slot = :slot " +
            "AND localWrittenAtEpochMs = :localGenerationEpochMs",
    )
    suspend fun markSyncedIfGenerationMatches(
        serverKey: String,
        userKey: String,
        romId: Long,
        romHash: String,
        slot: String,
        localGenerationEpochMs: Long,
        rommSaveId: Long?,
        serverHash: String?,
        serverSizeBytes: Long?,
        serverUpdatedAtEpochMs: Long?,
    ): Int

    @Query(
        "DELETE FROM save_replicas " +
            "WHERE serverKey = :serverKey AND userKey = :userKey " +
            "AND romId = :romId AND romHash = :romHash AND slot = :slot",
    )
    suspend fun deleteByScope(
        serverKey: String,
        userKey: String,
        romId: Long,
        romHash: String,
        slot: String,
    )
}
